<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Capture Screenshot Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="9.415">
  <properties />
            <testcase name="captureScreenshotAfterFailTest" time="9.415" classname="com.bjss.testcases.functional.CaptureScreenshotAfterFailTest">
                <failure type="java.lang.AssertionError"
                  message="The String : Spurs is meant to differ from: POPULAR to cause an intentional fail so a screenshot can be taken! expected [Spurs] but found [POPULAR]"
              >
<![CDATA[java.lang.AssertionError: The String : Spurs is meant to differ from: POPULAR to cause an intentional fail so a screenshot can be taken! expected [Spurs] but found [POPULAR]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:189)
  com.bjss.testcases.functional.CaptureScreenshotAfterFailTest.captureScreenshotAfterFailTest(CaptureScreenshotAfterFailTest.java:38)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
